declare module '@avocat-ai/shared' {
  export const AgentRunSchema: any;
  export const AgentRunRequestSchema: any;
  export const AgentStreamRequestSchema: any;
  export type AgentRun = any;
  export type ResearchStreamEvent = any;
  export const ResearchStreamPayloadSchema: any;
  export const ResearchDeskContextSchema: any;
  export type ResearchDeskContext = any;
  export type ResearchPlan = any;
  export type ResearchCitation = any;
  export const CitationsBrowserDataSchema: any;
  export type CitationDocument = any;
  export type CitationsBrowserData = any;
  export const CorpusDashboardDataSchema: any;
  export const HitlQueueDataSchema: any;
  export type HitlQueueData = any;
  export const MattersOverviewSchema: any;
  export type MattersOverview = any;
  export const PolicyConfigurationSchema: any;
  export const UploadResponseSchema: any;
  export const VoiceConsoleContextSchema: any;
  export const VoiceRunRequestSchema: any;
  export const VoiceRunResponseSchema: any;
  export const VoiceSessionTokenSchema: any;
  export type VoiceSessionToken = any;
  export type ProcessNavigatorFlow = any;
  export type WorkspaceDesk = any;
  export type OpenAIClientConfig = any;
  export function getOpenAIClient(config?: OpenAIClientConfig): any;
  export function isOpenAIDebugEnabled(): boolean;
  export function fetchOpenAIDebugDetails(client: any, error: unknown): Promise<any>;
  // Orchestrator types (temporary shims)
  export type ConnectorStatus = any;
  export type ConnectorType = any;
  export type DirectorCommandInput = any;
  export type OrchestratorCommandEnvelope = any;
  export type OrchestratorCommandRecord = any;
  export type OrchestratorCommandResponse = any;
  export type OrchestratorJobRecord = any;
  export type OrchestratorSessionRecord = any;
  export type OrgConnectorRecord = any;
  export type SafetyAssessmentResult = any;
  // Agent types (temporary shims)
  export type AgentPlanNotice = any;
  export type AgentPlanStep = any;
  export type IRACPayload = any;
  export type IRACSchema = any;
  export const OFFICIAL_DOMAIN_ALLOWLIST: string[];
}
