version: 2

updates:
  # Root workspace (monorepo-level dependencies)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    target-branch: "work"
    reviewers:
      - "avocat-ai/platform-squad"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "typescript"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "typescript"
        update-types:
          - "minor"
          - "patch"

  # apps/api
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: "work"
    reviewers:
      - "avocat-ai/platform-squad"
    labels:
      - "dependencies"
      - "area:backend"
      - "automated"
    commit-message:
      prefix: "chore(api)"

  # apps/web
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: "work"
    reviewers:
      - "avocat-ai/frontend-squad"
    labels:
      - "dependencies"
      - "area:frontend"
      - "automated"
    commit-message:
      prefix: "chore(web)"

  # apps/pwa
  - package-ecosystem: "npm"
    directory: "/apps/pwa"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: "work"
    reviewers:
      - "avocat-ai/frontend-squad"
    labels:
      - "dependencies"
      - "area:frontend"
      - "automated"
    commit-message:
      prefix: "chore(pwa)"

  # apps/ops
  - package-ecosystem: "npm"
    directory: "/apps/ops"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: "work"
    reviewers:
      - "avocat-ai/ops-team"
    labels:
      - "dependencies"
      - "area:infra"
      - "automated"
    commit-message:
      prefix: "chore(ops)"

  # apps/edge
  - package-ecosystem: "npm"
    directory: "/apps/edge"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: "work"
    reviewers:
      - "avocat-ai/platform-squad"
    labels:
      - "dependencies"
      - "area:backend"
      - "automated"
    commit-message:
      prefix: "chore(edge)"

  # packages/shared
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    target-branch: "work"
    reviewers:
      - "avocat-ai/platform-squad"
    labels:
      - "dependencies"
      - "area:backend"
      - "automated"
    commit-message:
      prefix: "chore(shared)"

  # packages/supabase
  - package-ecosystem: "npm"
    directory: "/packages/supabase"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    target-branch: "work"
    reviewers:
      - "avocat-ai/platform-squad"
    labels:
      - "dependencies"
      - "area:backend"
      - "automated"
    commit-message:
      prefix: "chore(supabase)"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: "work"
    reviewers:
      - "avocat-ai/platform-squad"
    labels:
      - "dependencies"
      - "area:infra"
      - "automated"
    commit-message:
      prefix: "chore(ci)"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    target-branch: "work"
    reviewers:
      - "avocat-ai/platform-squad"
    labels:
      - "dependencies"
      - "area:infra"
      - "automated"
    commit-message:
      prefix: "chore(docker)"
