repository:
  default_branch: work
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_squash_merge: true
  delete_branch_on_merge: true

branches:
  - name: work
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Monorepo CI / Full Workspace CI"
          - "Supabase Migration Smoke / Supabase Migration Smoke"
          - "Staging Smoke Tests / Staging Smoke Tests"
          - "Vercel Preview Build / Auto-create Preview"
          - "QA Sign-off / Require qa-signoff label"
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      block_creations: true
      lock_branch: false
      required_pull_request_reviews:
        require_code_owner_reviews: true
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_last_push_approval: true
        bypass_pull_request_allowances: {}
      restrictions: null
      required_conversation_resolution: true
