[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@8.15.4 --activate",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "cd apps/web && HOSTNAME=0.0.0.0 PORT=${PORT:-3000} NODE_ENV=production node .next/standalone/server.js"
