---
name: Bug Report
about: Report a bug or unexpected behavior
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: []
---

## Bug Description

<!-- A clear and concise description of what the bug is -->

## Steps to Reproduce

1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

## Expected Behavior

<!-- What you expected to happen -->

## Actual Behavior

<!-- What actually happened -->

## Environment

- **Node.js version**: <!-- e.g., 20.19.5 -->
- **pnpm version**: <!-- e.g., 8.15.4 -->
- **OS**: <!-- e.g., macOS 14, Ubuntu 22.04 -->
- **Browser** (if applicable): <!-- e.g., Chrome 120, Safari 17 -->
- **Deployment platform**: <!-- e.g., local, Vercel, Docker -->

## Logs / Error Messages

<!-- 
Paste relevant error messages or logs here.
Use triple backticks for code formatting.
REDACT any secrets or sensitive information.
-->

```
Error messages here
```

## Screenshots

<!-- If applicable, add screenshots to help explain the problem -->

## Additional Context

<!-- Any other relevant information about the problem -->

## Possible Solution

<!-- Optional: Suggest a fix or reason for the bug -->

## Checklist

- [ ] I have searched existing issues to ensure this is not a duplicate
- [ ] I have included steps to reproduce
- [ ] I have provided environment details
- [ ] I have redacted any sensitive information from logs
