blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability (Private)
    url: https://github.com/ikanisa/lawai/security/advisories/new
    about: Report a security vulnerability privately via GitHub Security Advisories
  - name: Question or Discussion
    url: https://github.com/ikanisa/lawai/discussions
    about: Ask questions or discuss ideas with the community
  - name: Support
    url: https://github.com/ikanisa/lawai/blob/main/SUPPORT.md
    about: Get help with installation, configuration, or troubleshooting
