blank_issues_enabled: false
contact_links:
  - name: 🔒 Security Vulnerability
    url: https://github.com/ikanisa/lawai/security/advisories/new
    about: Report security vulnerabilities privately through GitHub Security Advisories
  - name: 💬 Support Question
    url: https://github.com/ikanisa/lawai/blob/main/SUPPORT.md
    about: Get help and support - see SUPPORT.md for channels
  - name: 📚 Documentation
    url: https://github.com/ikanisa/lawai/tree/main/docs
    about: Browse documentation for architecture, operations, and deployment
