---
name: Feature Request
about: Suggest an idea or enhancement for this project
title: '[FEATURE] '
labels: ['enhancement', 'needs-triage']
assignees: []
---

## Feature Description

<!-- A clear and concise description of the feature you'd like to see -->

## Problem Statement

<!-- Describe the problem this feature would solve -->
<!-- Example: "I'm always frustrated when..." -->

## Proposed Solution

<!-- Describe how you envision this feature working -->

## Alternatives Considered

<!-- Describe any alternative solutions or features you've considered -->

## Use Cases

<!-- Who would benefit from this feature and how? -->

1. **Use case 1**: 
2. **Use case 2**: 

## Impact

<!-- What would be the impact if this feature is not implemented? -->

## Implementation Considerations

<!-- Optional: Technical details, dependencies, or concerns -->

### Affected Components

- [ ] apps/api (Fastify REST API)
- [ ] apps/web (Next.js operator console)
- [ ] apps/pwa (Next.js public PWA)
- [ ] apps/ops (CLI operational tooling)
- [ ] apps/edge (Supabase Edge Functions)
- [ ] packages/shared (Shared utilities)
- [ ] packages/supabase (Supabase types)
- [ ] Database migrations
- [ ] Documentation
- [ ] CI/CD

### Complexity Estimate

- [ ] Low (< 1 day)
- [ ] Medium (1-3 days)
- [ ] High (1 week)
- [ ] Very High (> 1 week)

## Additional Context

<!-- Any other context, mockups, or examples about the feature request -->

## Checklist

- [ ] I have searched existing issues to ensure this is not a duplicate
- [ ] I have described the problem this feature solves
- [ ] I have outlined potential use cases
- [ ] I have considered alternative solutions
