name: Refactor Task
description: Track a refactoring task for production readiness
title: "[Refactor]: "
labels: ["refactor", "go-live"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to track refactoring work for production and go-live readiness.

  - type: dropdown
    id: area
    attributes:
      label: Refactor Area
      description: Which area does this refactor address?
      options:
        - Architecture (module boundaries, layering)
        - Dependencies (upgrade, consolidate, remove)
        - Code Quality (linting, formatting, types)
        - Testing (coverage, determinism, pyramid)
        - Security (hardening, compliance, scanning)
        - Reliability (timeouts, retries, idempotency)
        - Performance (optimization, caching, baselines)
        - Observability (logging, metrics, tracing)
        - CI/CD (workflows, gates, automation)
        - Documentation (architecture, runbooks, READMEs)
        - Infrastructure (containers, IaC, deployment)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Blocking level for go-live
      options:
        - S0 - Critical (blocks go-live)
        - S1 - High (should fix before go-live)
        - S2 - Medium (nice to have before go-live)
        - S3 - Low (can defer post go-live)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what needs to be refactored and why
      placeholder: |
        Current state: ...
        Target state: ...
        Rationale: ...
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What files, modules, or components are affected?
      placeholder: |
        Files to change:
        - apps/api/src/...
        - packages/shared/...
        
        Estimated LOC affected: ...
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: Approach
      description: High-level approach to the refactor
      placeholder: |
        1. Step one...
        2. Step two...
        3. ...

  - type: textarea
    id: risks
    attributes:
      label: Risks
      description: What could go wrong? What are the risks?
      placeholder: |
        - Risk 1: ... (mitigation: ...)
        - Risk 2: ... (mitigation: ...)

  - type: textarea
    id: testing
    attributes:
      label: Testing Strategy
      description: How will you validate the refactor?
      placeholder: |
        - Characterization tests before refactor
        - Unit tests for new structure
        - Integration tests for...
        - Manual testing: ...

  - type: textarea
    id: migration
    attributes:
      label: Migration Notes
      description: Any migration steps required? Breaking changes?
      placeholder: |
        Breaking changes: Yes/No
        
        If yes:
        - What breaks: ...
        - Migration steps: ...
        - Deprecation timeline: ...

  - type: textarea
    id: rollback
    attributes:
      label: Rollback Plan
      description: How can this be rolled back if needed?
      placeholder: |
        Rollback strategy: ...
        Steps: ...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Primary component affected
      options:
        - apps/api
        - apps/web
        - apps/pwa
        - apps/ops
        - apps/edge
        - packages/shared
        - packages/supabase
        - packages/compliance
        - packages/observability
        - CI/CD
        - Documentation
        - Infrastructure
        - Cross-cutting
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Does this depend on other refactors or issues?
      placeholder: |
        Depends on:
        - #123
        - #456
        
        Blocks:
        - #789

  - type: textarea
    id: estimate
    attributes:
      label: Effort Estimate
      description: How long will this take?
      placeholder: |
        Complexity: Low/Medium/High
        Estimated time: X days/weeks
        Can be split: Yes/No

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What must be true for this refactor to be complete?
      options:
        - label: Code changes implemented and tested
        - label: Tests added/updated (coverage maintained/improved)
        - label: Documentation updated
        - label: CI/CD passes
        - label: Code review approved
        - label: Migration notes in PR description
        - label: No regression in existing behavior
        - label: Performance benchmarks maintained/improved
