---
name: Security Vulnerability
about: Report a security vulnerability (use responsibly)
title: '[SECURITY] '
labels: ['security', 'needs-triage']
assignees: []
---

## ⚠️ SECURITY NOTICE

**If this is a critical or high-severity vulnerability, please report it privately:**
- Use GitHub Security Advisory: "Report a vulnerability" in the Security tab
- Or email: security@avocat-ai.example (replace with actual contact)

**Only use this public template for LOW severity findings that do not pose immediate risk.**

---

## Vulnerability Type

<!-- Check the applicable vulnerability type -->

- [ ] XSS (Cross-Site Scripting)
- [ ] SQL Injection
- [ ] CSRF (Cross-Site Request Forgery)
- [ ] Authentication Bypass
- [ ] Authorization Issue
- [ ] Information Disclosure
- [ ] Denial of Service
- [ ] Dependency Vulnerability
- [ ] Configuration Issue
- [ ] Other (please describe)

## Severity Assessment

<!-- Your assessment of the severity -->

- [ ] Critical (S0) - Immediate exploitation, data breach risk
- [ ] High (S1) - Significant security risk
- [ ] Medium (S2) - Moderate security risk
- [ ] Low (S3) - Minor security concern

## Affected Component

<!-- Which part of the system is affected? -->

- **Component**: <!-- e.g., apps/api, apps/web, apps/pwa -->
- **File(s)**: <!-- e.g., apps/api/src/routes/admin.ts -->
- **Version**: <!-- e.g., v1.2.3, commit SHA -->

## Description

<!-- Clear description of the vulnerability -->

## Steps to Reproduce

<!-- Detailed steps to reproduce the vulnerability -->

1. 
2. 
3. 

## Proof of Concept

<!-- 
Optional: Code or screenshots demonstrating the vulnerability
DO NOT include actual exploit code for critical vulnerabilities
-->

## Impact

<!-- What is the potential impact if exploited? -->

- **Data at risk**: 
- **Affected users**: 
- **Attack complexity**: 

## Proposed Mitigation

<!-- Optional: Suggestions for fixing the vulnerability -->

## References

<!-- Optional: Links to CVEs, similar vulnerabilities, or documentation -->

- 
- 

## Checklist

- [ ] I have assessed this as LOW severity (or reported privately if higher)
- [ ] I have NOT included exploit code for critical vulnerabilities
- [ ] I have described the potential impact
- [ ] I have provided reproduction steps
- [ ] I have suggested mitigation approaches (optional)
