// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttbjgzzabnecihoeqrtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0YmpnenphYm5lY2lob2VxcnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTE3MTksImV4cCI6MjA3NDUyNzcxOX0.9nVyIaZvaKhvJ9YeCpqY0JjuPKNT5iR2ZJZUCVG3vkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});