import type { WorkspaceDesk } from '@avocat-ai/shared';

export function buildPhaseCWorkspaceDesk(): WorkspaceDesk {
  return {
    playbooks: [
      {
        id: 'fr-civil-claim',
        title: 'Process Navigator · Civil claim (FR)',
        persona: 'Process Navigator',
        jurisdiction: 'FR',
        mode: 'ask',
        summary:
          'Guide litigators through FR civil claim intake with FRIA evidence, CEPEJ charter checks, and OHADA override handling before drafting filings.',
        regulatoryFocus: [
          'FRIA ingestion + consent evidence',
          'CEPEJ charter assertions + EU AI Act audit logging',
          'Maghreb binding-language banner + OHADA pre-emption review',
        ],
        steps: [
          {
            id: 'fria-intake',
            name: 'FRIA intake + consent capture',
            description: 'Pull FRIA dossier, record consent banner acceptance, and confirm Council of Europe disclosures.',
            status: 'success',
            attempts: 1,
            detail: {
              tools: ['fria_ingestor', 'consent_banner_audit'],
              outputs: ['fria_dossier.json', 'consent_log.pdf'],
            },
          },
          {
            id: 'cepej-charter',
            name: 'CEPEJ charter & EU AI Act tests',
            description: 'Run CEPEJ automated charter scenarios and log EU AI Act guardrail attestations.',
            status: 'success',
            attempts: 1,
            detail: {
              tools: ['cepej_charter_suite'],
              assertions: ['statute-first', 'confidential-mode'],
            },
          },
          {
            id: 'ohada-preemption',
            name: 'OHADA pre-emption scan',
            description: 'Cross-check Maghreb filings against OHADA precedence and binding-language banners before escalation.',
            status: 'success',
            attempts: 1,
            detail: {
              tools: ['ohada_alignment_service'],
              outputs: ['binding_language_banner.html'],
            },
          },
        ],
        cta: {
          label: 'Launch in Ask mode',
          question: 'Quels délais et pièces pour une assignation civile à Paris 2024 ?',
          mode: 'ask',
        },
      },
      {
        id: 'ohada-debt-recovery',
        title: 'Process Navigator · OHADA debt recovery',
        persona: 'Process Navigator',
        jurisdiction: 'OHADA',
        mode: 'do',
        summary:
          'Structure debt recovery under AUSCGIE with statute alignment, Maghreb residency flags, and political risk overlays.',
        regulatoryFocus: [
          'AUSCGIE statute alignment',
          'Residency & binding-language banners',
          'Political risk indicators (Maghreb & CEMAC)',
        ],
        steps: [
          {
            id: 'statute-alignment',
            name: 'Statute-first alignment',
            description: 'Prioritise AUSCGIE citations and reject unverified commentary.',
            status: 'success',
            attempts: 1,
            detail: {
              tools: ['statute_alignment'],
              outputs: ['alignment_snapshot.json'],
            },
          },
          {
            id: 'treatment-graph',
            name: 'Treatment graph generation',
            description: 'Plot recent CCJA treatment graph with weightings and drift detection.',
            status: 'success',
            attempts: 1,
            detail: {
              tools: ['case_graph_builder'],
              outputs: ['treatment_graph.svg'],
            },
          },
          {
            id: 'political-risk',
            name: 'Political risk flags',
            description: 'Surface Maghreb binding-language banners and political risk flags prior to negotiation.',
            status: 'success',
            attempts: 1,
            detail: {
              tools: ['risk_overlay_service'],
              outputs: ['political_risk_flags.json'],
            },
          },
        ],
        cta: {
          label: 'Launch in Do mode',
          question: 'Préparer une mise en demeure OHADA pour recouvrement de créance.',
          mode: 'do',
        },
      },
    ],
    quickActions: [
      {
        id: 'deadline-calculator',
        label: 'Deadline calculator',
        description: 'Send facts to the matters workspace to compute jurisdictional deadlines.',
        mode: 'do',
        action: 'navigate',
        href: '/matters',
      },
      {
        id: 'filing-studio',
        label: 'Filing prep studio',
        description: 'Jump to drafting with statute-aligned templates and live redlines.',
        mode: 'generate',
        action: 'navigate',
        href: '/drafting',
      },
      {
        id: 'cite-check',
        label: 'Cite-check & diff',
        description: 'Open the citations diff viewer to verify binding sources before export.',
        mode: 'review',
        action: 'navigate',
        href: '/citations',
      },
      {
        id: 'open-plan',
        label: 'Agent plan snapshot',
        description: 'Reveal the latest agent steps, tool calls, and guardrails.',
        mode: 'ask',
        action: 'plan',
      },
      {
        id: 'trust-dashboard',
        label: 'Trust & fairness dashboard',
        description: 'Inspect retrieval trust and fairness trends for regulators.',
        mode: 'review',
        action: 'trust',
        href: '/trust',
      },
      {
        id: 'hitl-cta',
        label: 'HITL queue',
        description: 'Escalate or approve pending runs in the reviewer console.',
        mode: 'review',
        action: 'hitl',
        href: '/hitl',
      },
    ],
    personas: [
      {
        id: 'bench-memo',
        label: 'Bench memo specialist',
        description: 'Synthesises bench memos with statute-first evidence and Maghreb bilingual flags.',
        mode: 'review',
        focusAreas: ['Statute alignment', 'Political risk overlays', 'Confidential mode'],
        guardrails: ['France judge analytics blocked', 'OHADA pre-emption enforced'],
        href: '/research?persona=bench_memo',
        agentCode: 'bench_memo',
      },
      {
        id: 'procedural-navigator',
        label: 'Procedural navigator',
        description: 'Walks litigants through filing steps, consent capture, and residency compliance.',
        mode: 'ask',
        focusAreas: ['FRIA consent logging', 'CEPEJ disclosures', 'Residency dashboards'],
        guardrails: ['Statute-first cite-or-refuse', 'Confidential evidence segregation'],
        href: '/workspace?persona=procedural_navigator',
        agentCode: 'procedural_navigator',
      },
      {
        id: 'negotiation-mediator',
        label: 'Negotiation mediator',
        description: 'Balances settlement options with political risk and fairness telemetry.',
        mode: 'do',
        focusAreas: ['Treatment graph comparisons', 'Synonym drift analytics', 'Binding language prompts'],
        guardrails: ['Maghreb banners pinned', 'OHADA precedence before offers'],
        href: '/drafting?persona=negotiation_mediator',
        agentCode: 'negotiation_mediator',
      },
      {
        id: 'evidence-discovery',
        label: 'Evidence discovery',
        description: 'Surfaces ELI/ECLI/Akoma Ntoso provenance with quarantine dashboards.',
        mode: 'ask',
        focusAreas: ['Akoma Ntoso tagging', 'Quarantine dashboards', 'Residency completeness'],
        guardrails: ['Confidential mode locked', 'Statute-first retrieval thresholds'],
        href: '/corpus?persona=evidence_discovery',
        agentCode: 'evidence_discovery',
      },
    ],
    toolChips: [
      {
        id: 'mode-ask',
        label: 'Ask mode',
        mode: 'ask',
        status: 'ready',
        description: 'Command palette + plan drawer wired for FRIA and CEPEJ compliance evidence.',
        action: 'plan',
        ctaLabel: 'Open plan drawer',
      },
      {
        id: 'mode-do',
        label: 'Do mode',
        mode: 'do',
        status: 'monitoring',
        description: 'Deadline wizard and matters workspace logging telemetry hourly.',
        action: 'navigate',
        href: '/matters',
        ctaLabel: 'Open matters workspace',
      },
      {
        id: 'mode-review',
        label: 'Review mode',
        mode: 'review',
        status: 'requires_hitl',
        description: 'HITL queue flagged due to recent political-risk spikes in Maghreb feeds.',
        action: 'hitl',
        href: '/hitl',
        ctaLabel: 'Review queue',
      },
      {
        id: 'mode-generate',
        label: 'Generate mode',
        mode: 'generate',
        status: 'ready',
        description: 'Drafting studio exports covered by C2PA signing and cite-check diff viewer.',
        action: 'navigate',
        href: '/drafting',
        ctaLabel: 'Open drafting studio',
      },
      {
        id: 'mode-trust',
        label: 'Trust signals',
        mode: 'review',
        status: 'monitoring',
        description: 'Trust dashboard streaming fairness + synonym telemetry for regulators.',
        action: 'trust',
        href: '/trust',
        ctaLabel: 'Open trust dashboard',
      },
    ],
  };
}
