import type { ProcessNavigatorFlow, WorkspaceDesk } from '@avocat-ai/shared';

export function buildPhaseCWorkspaceDesk(): WorkspaceDesk {
  return {
    playbooks: [
      {
        id: 'fr-civil-claim',
        title: 'Process Navigator · Civil claim (FR)',
        persona: 'Process Navigator',
        jurisdiction: 'FR',
        mode: 'ask',
        summary:
          'Guide litigators through FR civil claim intake with FRIA evidence, CEPEJ charter checks, and OHADA override handling before drafting filings.',
        regulatoryFocus: [
          'FRIA ingestion + consent evidence',
          'CEPEJ charter assertions + EU AI Act audit logging',
          'Maghreb binding-language banner + OHADA pre-emption review',
        ],
        steps: [
          {
            id: 'fria-intake',
            name: 'FRIA intake + consent capture',
            description: 'Pull FRIA dossier, record consent banner acceptance, and confirm Council of Europe disclosures.',
            status: 'success',
            attempts: 1,
            detail: {
              tools: ['fria_ingestor', 'consent_banner_audit'],
              outputs: ['fria_dossier.json', 'consent_log.pdf'],
            },
          },
          {
            id: 'cepej-charter',
            name: 'CEPEJ charter & EU AI Act tests',
            description: 'Run CEPEJ automated charter scenarios and log EU AI Act guardrail attestations.',
            status: 'success',
            attempts: 1,
            detail: {
              tools: ['cepej_charter_suite'],
              assertions: ['statute-first', 'confidential-mode'],
            },
          },
          {
            id: 'ohada-preemption',
            name: 'OHADA pre-emption scan',
            description: 'Cross-check Maghreb filings against OHADA precedence and binding-language banners before escalation.',
            status: 'success',
            attempts: 1,
            detail: {
              tools: ['ohada_alignment_service'],
              outputs: ['binding_language_banner.html'],
            },
          },
        ],
        cta: {
          label: 'Launch in Ask mode',
          question: 'Quels délais et pièces pour une assignation civile à Paris 2024 ?',
          mode: 'ask',
        },
      },
      {
        id: 'ohada-debt-recovery',
        title: 'Process Navigator · OHADA debt recovery',
        persona: 'Process Navigator',
        jurisdiction: 'OHADA',
        mode: 'do',
        summary:
          'Structure debt recovery under AUSCGIE with statute alignment, Maghreb residency flags, and political risk overlays.',
        regulatoryFocus: [
          'AUSCGIE statute alignment',
          'Residency & binding-language banners',
          'Political risk indicators (Maghreb & CEMAC)',
        ],
        steps: [
          {
            id: 'statute-alignment',
            name: 'Statute-first alignment',
            description: 'Prioritise AUSCGIE citations and reject unverified commentary.',
            status: 'success',
            attempts: 1,
            detail: {
              tools: ['statute_alignment'],
              outputs: ['alignment_snapshot.json'],
            },
          },
          {
            id: 'treatment-graph',
            name: 'Treatment graph generation',
            description: 'Plot recent CCJA treatment graph with weightings and drift detection.',
            status: 'success',
            attempts: 1,
            detail: {
              tools: ['case_graph_builder'],
              outputs: ['treatment_graph.svg'],
            },
          },
          {
            id: 'political-risk',
            name: 'Political risk flags',
            description: 'Surface Maghreb binding-language banners and political risk flags prior to negotiation.',
            status: 'success',
            attempts: 1,
            detail: {
              tools: ['risk_overlay_service'],
              outputs: ['political_risk_flags.json'],
            },
          },
        ],
        cta: {
          label: 'Launch in Do mode',
          question: 'Préparer une mise en demeure OHADA pour recouvrement de créance.',
          mode: 'do',
        },
      },
    ],
    quickActions: [
      {
        id: 'deadline-calculator',
        label: 'Deadline calculator',
        description: 'Send facts to the matters workspace to compute jurisdictional deadlines.',
        mode: 'do',
        action: 'navigate',
        href: '/matters',
      },
      {
        id: 'filing-studio',
        label: 'Filing prep studio',
        description: 'Jump to drafting with statute-aligned templates and live redlines.',
        mode: 'generate',
        action: 'navigate',
        href: '/drafting',
      },
      {
        id: 'cite-check',
        label: 'Cite-check & diff',
        description: 'Open the citations diff viewer to verify binding sources before export.',
        mode: 'review',
        action: 'navigate',
        href: '/citations',
      },
      {
        id: 'open-plan',
        label: 'Agent plan snapshot',
        description: 'Reveal the latest agent steps, tool calls, and guardrails.',
        mode: 'ask',
        action: 'plan',
      },
      {
        id: 'trust-dashboard',
        label: 'Trust & fairness dashboard',
        description: 'Inspect retrieval trust and fairness trends for regulators.',
        mode: 'review',
        action: 'trust',
        href: '/trust',
      },
      {
        id: 'hitl-cta',
        label: 'HITL queue',
        description: 'Escalate or approve pending runs in the reviewer console.',
        mode: 'review',
        action: 'hitl',
        href: '/hitl',
      },
    ],
    personas: [
      {
        id: 'bench-memo',
        label: 'Bench memo specialist',
        description: 'Synthesises bench memos with statute-first evidence and Maghreb bilingual flags.',
        mode: 'review',
        focusAreas: ['Statute alignment', 'Political risk overlays', 'Confidential mode'],
        guardrails: ['France judge analytics blocked', 'OHADA pre-emption enforced'],
        href: '/research?persona=bench_memo',
        agentCode: 'bench_memo',
      },
      {
        id: 'procedural-navigator',
        label: 'Procedural navigator',
        description: 'Walks litigants through filing steps, consent capture, and residency compliance.',
        mode: 'ask',
        focusAreas: ['FRIA consent logging', 'CEPEJ disclosures', 'Residency dashboards'],
        guardrails: ['Statute-first cite-or-refuse', 'Confidential evidence segregation'],
        href: '/workspace?persona=procedural_navigator',
        agentCode: 'procedural_navigator',
      },
      {
        id: 'negotiation-mediator',
        label: 'Negotiation mediator',
        description: 'Balances settlement options with political risk and fairness telemetry.',
        mode: 'do',
        focusAreas: ['Treatment graph comparisons', 'Synonym drift analytics', 'Binding language prompts'],
        guardrails: ['Maghreb banners pinned', 'OHADA precedence before offers'],
        href: '/drafting?persona=negotiation_mediator',
        agentCode: 'negotiation_mediator',
      },
      {
        id: 'evidence-discovery',
        label: 'Evidence discovery',
        description: 'Surfaces ELI/ECLI/Akoma Ntoso provenance with quarantine dashboards.',
        mode: 'ask',
        focusAreas: ['Akoma Ntoso tagging', 'Quarantine dashboards', 'Residency completeness'],
        guardrails: ['Confidential mode locked', 'Statute-first retrieval thresholds'],
        href: '/corpus?persona=evidence_discovery',
        agentCode: 'evidence_discovery',
      },
    ],
    toolChips: [
      {
        id: 'mode-ask',
        label: 'Ask mode',
        mode: 'ask',
        status: 'ready',
        description: 'Command palette + plan drawer wired for FRIA and CEPEJ compliance evidence.',
        action: 'plan',
        ctaLabel: 'Open plan drawer',
      },
      {
        id: 'mode-do',
        label: 'Do mode',
        mode: 'do',
        status: 'monitoring',
        description: 'Deadline wizard and matters workspace logging telemetry hourly.',
        action: 'navigate',
        href: '/matters',
        ctaLabel: 'Open matters workspace',
      },
      {
        id: 'mode-review',
        label: 'Review mode',
        mode: 'review',
        status: 'requires_hitl',
        description: 'HITL queue flagged due to recent political-risk spikes in Maghreb feeds.',
        action: 'hitl',
        href: '/hitl',
        ctaLabel: 'Review queue',
      },
      {
        id: 'mode-generate',
        label: 'Generate mode',
        mode: 'generate',
        status: 'ready',
        description: 'Drafting studio exports covered by C2PA signing and cite-check diff viewer.',
        action: 'navigate',
        href: '/drafting',
        ctaLabel: 'Open drafting studio',
      },
      {
        id: 'mode-trust',
        label: 'Trust signals',
        mode: 'review',
        status: 'monitoring',
        description: 'Trust dashboard streaming fairness + synonym telemetry for regulators.',
        action: 'trust',
        href: '/trust',
        ctaLabel: 'Open trust dashboard',
      },
    ],
  };
}

export function buildPhaseCProcessNavigator(): ProcessNavigatorFlow[] {
  return [
    {
      id: 'fr-civil-claim',
      title: 'Assignation civile – Tribunal judiciaire de Paris',
      jurisdiction: 'FR',
      persona: 'procedural_navigator',
      mode: 'ask',
      summary:
        'Prépare l’assignation civile avec ingestion FRIA, attestations CEPEJ et revue OHADA avant dépôt.',
      estimatedMinutes: 45,
      lastRunAt: '2025-10-12T09:30:00.000Z',
      alerts: [
        'Confirmer le consentement CEPEJ avant la génération du brouillon.',
        'HITL requis si le dossier FRIA contient des pièces confidentielles non validées.',
      ],
      telemetry: {
        runCount: 18,
        hitlEscalations: 2,
        pendingTasks: 1,
      },
      steps: [
        {
          id: 'fria-intake',
          label: 'Ingestion FRIA et consentements',
          description:
            'Importer le dossier FRIA, enregistrer le consentement CEPEJ et vérifier les engagements Conseil de l’Europe.',
          state: 'complete',
          guardrails: ['Consentement CEPEJ journalisé', 'Mode confidentiel activé'],
          outputs: ['fria_dossier.json', 'consent_log.pdf'],
        },
        {
          id: 'evidence-triage',
          label: 'Tri des pièces et bilinguisme',
          description:
            'Évaluer les pièces jointes, appliquer les bannières langue Maghreb et confirmer la résidence des données.',
          state: 'complete',
          guardrails: ['Residency FR/EU respectée', 'Bannières langue Maghreb visibles'],
          outputs: ['evidence_manifest.csv'],
        },
        {
          id: 'cepej-audit',
          label: 'Audit CEPEJ et EU AI Act',
          description:
            'Exécuter les scénarios CEPEJ et journaliser les attestations EU AI Act pour le Go/No-Go.',
          state: 'in_progress',
          guardrails: ['Scénarios CEPEJ verts', 'Attestations EU AI Act stockées'],
          outputs: ['cepej_audit_report.json'],
        },
        {
          id: 'drafting-brief',
          label: 'Préparation du projet d’assignation',
          description:
            'Assembler le brouillon de l’assignation avec sources statutaires et citations OHADA.',
          state: 'in_progress',
          guardrails: ['Statute-first enforcé', 'Signatures C2PA demandées'],
          outputs: ['assignation_draft.docx'],
        },
        {
          id: 'hitl-review',
          label: 'Revue HITL et dépôt',
          description:
            'Acheminer la version finale vers la file HITL et capturer la validation avant dépôt tribunal.',
          state: 'blocked',
          guardrails: ['Validation reviewer requise'],
          outputs: ['hitl_ticket.json'],
          escalation: 'HITL en attente pour raisons de confidentialité',
        },
      ],
    },
    {
      id: 'ohada-debt-recovery',
      title: 'Recouvrement de créance – OHADA',
      jurisdiction: 'OHADA',
      persona: 'negotiation_mediator',
      mode: 'do',
      summary:
        'Structure la mise en demeure OHADA avec priorisation AUSCGIE, graphes de traitement CCJA et signaux politiques.',
      estimatedMinutes: 35,
      lastRunAt: '2025-10-11T16:05:00.000Z',
      alerts: ['Suivi des risques politiques Maghreb/CEMAC recommandé avant négociation.'],
      telemetry: {
        runCount: 12,
        hitlEscalations: 1,
        pendingTasks: 0,
      },
      steps: [
        {
          id: 'statute-analysis',
          label: 'Analyse AUSCGIE',
          description: 'Aligner la requête sur les articles AUSCGIE pertinents et rejeter les sources non officielles.',
          state: 'complete',
          guardrails: ['Statute-first enforcé'],
          outputs: ['auscgie_alignment.pdf'],
        },
        {
          id: 'treatment-graph',
          label: 'Graphes CCJA',
          description:
            'Générer le graphe de traitement CCJA avec pondération temporelle et détecter les dérives récentes.',
          state: 'complete',
          guardrails: ['Drift monitoring actif'],
          outputs: ['ccja_treatment.svg'],
        },
        {
          id: 'political-risk',
          label: 'Surveillance risque politique',
          description:
            'Appliquer les alertes politiques Maghreb/CEMAC et journaliser les signaux négociation.',
          state: 'in_progress',
          guardrails: ['Aucun transfert hors zone autorisée'],
          outputs: ['political_risk.json'],
        },
        {
          id: 'draft-demand',
          label: 'Rédaction mise en demeure',
          description: 'Assembler la lettre de mise en demeure avec variantes bilingues et références CCJA.',
          state: 'in_progress',
          guardrails: ['Mention bilingue Maghreb obligatoire'],
          outputs: ['mise_en_demeure.docx'],
        },
        {
          id: 'settlement-brief',
          label: 'Brief de négociation',
          description: 'Préparer les options de règlement et déclencher la génération du plan de négociation.',
          state: 'complete',
          guardrails: ['Fairness telemetry capturée'],
          outputs: ['settlement_brief.pdf'],
        },
      ],
    },
    {
      id: 'employment-dismissal',
      title: 'Licenciement économique – France',
      jurisdiction: 'FR',
      persona: 'bench_memo',
      mode: 'review',
      summary:
        'Crée un mémo de licenciement économique avec analyse IRAC, obligations sociales et suivi HITL.',
      estimatedMinutes: 50,
      lastRunAt: '2025-10-10T08:15:00.000Z',
      alerts: ['Vérifier la couverture convention collective et la consultation CSE.'],
      telemetry: {
        runCount: 9,
        hitlEscalations: 3,
        pendingTasks: 2,
      },
      steps: [
        {
          id: 'fact-intake',
          label: 'Collecte faits & contrats',
          description: 'Ingestion des contrats de travail et catégorisation des postes impactés.',
          state: 'complete',
          guardrails: ['Données personnelles pseudonymisées'],
          outputs: ['employment_facts.json'],
        },
        {
          id: 'collective-agreements',
          label: 'Analyse conventions collectives',
          description: 'Identifier les obligations issues des conventions collectives applicables.',
          state: 'in_progress',
          guardrails: ['Interprétations validées HITL'],
          outputs: ['collective_matrix.xlsx'],
          escalation: 'Review CSE en cours',
        },
        {
          id: 'social-plan',
          label: 'Plan social & mesures',
          description: 'Élaborer un plan social et calculer les indemnités minimales.',
          state: 'in_progress',
          guardrails: ['Calculs indemnités >= seuil légal'],
          outputs: ['social_plan.docx'],
        },
        {
          id: 'irac-brief',
          label: 'Rédaction mémo IRAC',
          description: 'Générer le mémo IRAC avec citations officielles et résumés jurisprudentiels.',
          state: 'blocked',
          guardrails: ['Validation fairness & drift requise'],
          outputs: ['memo_irac.docx'],
          escalation: 'En attente d’un reviewer senior',
        },
        {
          id: 'export-c2pa',
          label: 'Export & signature C2PA',
          description: 'Préparer les exports PDF/DOCX avec signature C2PA et log d’audit.',
          state: 'in_progress',
          guardrails: ['Manifestes C2PA validés'],
          outputs: ['memo_irac_signed.pdf'],
        },
      ],
    },
    {
      id: 'ohada-company-formation',
      title: 'Création de société – OHADA',
      jurisdiction: 'OHADA',
      persona: 'procedural_navigator',
      mode: 'do',
      summary:
        'Guide la constitution d’une SARL OHADA avec statuts bilingues, registres UEMOA et contrôles de résidence.',
      estimatedMinutes: 60,
      lastRunAt: '2025-10-09T14:40:00.000Z',
      alerts: ['Assurer la domiciliation approuvée avant signature des statuts.'],
      telemetry: {
        runCount: 7,
        hitlEscalations: 1,
        pendingTasks: 1,
      },
      steps: [
        {
          id: 'intake',
          label: 'Collecte fondateurs & apports',
          description: 'Enregistrer les fondateurs, apports et mandats associés.',
          state: 'complete',
          guardrails: ['Vérification KYC réussie'],
          outputs: ['founders_register.json'],
        },
        {
          id: 'statutes-draft',
          label: 'Rédaction statuts bilingues',
          description: 'Générer les statuts en FR/EN avec clauses de gouvernance OHADA.',
          state: 'in_progress',
          guardrails: ['Terminologie OHADA validée'],
          outputs: ['statuts_draft.docx'],
        },
        {
          id: 'registries',
          label: 'Dépôt registres & RCCM',
          description: 'Préparer les dépôts RCCM/UEMOA et vérifier les délais légaux.',
          state: 'in_progress',
          guardrails: ['Délais RCCM monitorés'],
          outputs: ['rccm_submission.json'],
        },
        {
          id: 'tax-registration',
          label: 'Enregistrement fiscal',
          description: 'Générer les formulaires fiscaux et planifier la télédéclaration.',
          state: 'blocked',
          guardrails: ['Validation résidence fiscale requise'],
          outputs: ['tax_forms.pdf'],
          escalation: 'Attente attestation résidence',
        },
        {
          id: 'handoff',
          label: 'Remise dossier opérateur',
          description: 'Partager le dossier complet avec l’équipe opérations et déclencher l’outbox offline.',
          state: 'in_progress',
          guardrails: ['Journalisation Go/No-Go'],
          outputs: ['formation_package.zip'],
        },
      ],
    },
    {
      id: 'rwanda-commercial-lease',
      title: 'Bail commercial – Rwanda',
      jurisdiction: 'RW',
      persona: 'evidence_discovery',
      mode: 'ask',
      summary:
        'Assemble les baux commerciaux avec obligations bilingues, vérification résidence et contrôles C2PA.',
      estimatedMinutes: 32,
      lastRunAt: '2025-10-08T11:20:00.000Z',
      alerts: ['Activer le mode confidentiel avant la diffusion du brouillon au client.'],
      telemetry: {
        runCount: 11,
        hitlEscalations: 0,
        pendingTasks: 0,
      },
      steps: [
        {
          id: 'jurisdiction-check',
          label: 'Vérification juridiction & langue',
          description: 'Valider la langue obligatoire (RW/EN) et activer les bannières de résidence Rwanda.',
          state: 'complete',
          guardrails: ['Mode confidentiel forcé', 'Residency Rwanda confirmée'],
          outputs: ['jurisdiction_report.json'],
        },
        {
          id: 'template-selection',
          label: 'Sélection modèle',
          description: 'Choisir le modèle de bail adapté avec métadonnées Akoma Ntoso.',
          state: 'complete',
          guardrails: ['Sources officielles uniquement'],
          outputs: ['template_metadata.json'],
        },
        {
          id: 'drafting',
          label: 'Rédaction bilingue',
          description: 'Rédiger le bail et générer les résumés FR/EN pour revue client.',
          state: 'in_progress',
          guardrails: ['Citations alignées', 'Traductions validées'],
          outputs: ['draft_lease.docx'],
        },
        {
          id: 'evidence-bundle',
          label: 'Assemblage pièces',
          description: 'Assembler les pièces justificatives et appliquer signatures C2PA.',
          state: 'in_progress',
          guardrails: ['Signatures C2PA requises'],
          outputs: ['evidence_bundle.zip'],
        },
        {
          id: 'delivery',
          label: 'Remise client & métriques',
          description: 'Partager le package avec métriques fairness et journalisation Go/No-Go.',
          state: 'complete',
          guardrails: ['Telemetry fairness enregistrée'],
          outputs: ['delivery_receipt.json'],
        },
      ],
    },
  ];
}
