name: Main Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: main-pipeline-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-ci.yml
