name: Pull Request Pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pr-pipeline-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-ci.yml
