name: Generate SBOM

on:
  push:
    branches: [ main, master, work ]
  pull_request:
    branches: [ main, master, work ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  generate-sbom:
    name: Generate Software Bill of Materials
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.15.4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --ignore-scripts

    # Generate SBOM using CycloneDX format (industry standard)
    - name: Generate CycloneDX SBOM
      run: |
        echo "Installing CycloneDX generator..."
        pnpm add -g @cyclonedx/cyclonedx-npm
        
        echo "Generating SBOM..."
        mkdir -p sbom-output
        
        # Generate SBOM for root
        cyclonedx-npm --output-file sbom-output/sbom-root.json
        
        # Generate SBOM for each workspace (optional, can be large)
        # for workspace in apps/api apps/web apps/pwa apps/ops packages/shared packages/supabase; do
        #   if [ -d "$workspace" ]; then
        #     echo "Generating SBOM for $workspace..."
        #     cd "$workspace"
        #     cyclonedx-npm --output-file "../../sbom-output/sbom-$(basename $workspace).json"
        #     cd ../..
        #   fi
        # done
        
        echo "SBOM generation complete"

    # Generate SBOM using SPDX format (alternative format)
    - name: Generate SPDX SBOM
      run: |
        echo "Installing SPDX SBOM generator..."
        npm install -g @microsoft/sbom-tool
        
        echo "Generating SPDX SBOM..."
        sbom-tool generate \
          -b ./sbom-output \
          -bc . \
          -pn "avocat-ai-monorepo" \
          -pv "$(git describe --tags --always)" \
          -ps "ikanisa" \
          -nsb "https://github.com/ikanisa/lawai" \
          -V Verbose || echo "SPDX generation may have warnings"
      continue-on-error: true

    # Generate a human-readable dependency list
    - name: Generate dependency list
      run: |
        echo "Generating human-readable dependency list..."
        echo "# Avocat-AI Dependencies" > sbom-output/dependencies.md
        echo "" >> sbom-output/dependencies.md
        echo "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> sbom-output/dependencies.md
        echo "Commit: ${{ github.sha }}" >> sbom-output/dependencies.md
        echo "" >> sbom-output/dependencies.md
        echo "## Production Dependencies" >> sbom-output/dependencies.md
        pnpm list --prod --depth=1 >> sbom-output/dependencies.md || true
        echo "" >> sbom-output/dependencies.md
        echo "## Development Dependencies" >> sbom-output/dependencies.md
        pnpm list --dev --depth=1 >> sbom-output/dependencies.md || true

    steps:
    - name: Download SBOM artifacts
      uses: actions/download-artifact@v6
      with:
        name: sbom-${{ github.sha }}
        path: ./sbom

    - name: Verify SBOM files
      run: |
        echo "Verifying SBOM files..."
        
        # Check if main SBOM file exists
        if [ -f "sbom/sbom-root.json" ]; then
          echo "✅ Main SBOM file found"
          # Validate JSON format
          cat sbom/sbom-root.json | jq . > /dev/null && echo "✅ SBOM JSON is valid"
        else
          echo "❌ Main SBOM file not found"
          exit 1
        fi
        
        # Check dependency list
        if [ -f "sbom/dependencies.md" ]; then
          echo "✅ Dependency list found"
          DEPS=$(cat sbom/dependencies.md | wc -l)
          echo "  Dependencies listed: $DEPS lines"
        fi
        
        # Check license report
        if [ -f "sbom/licenses.md" ]; then
          echo "✅ License report found"
        fi
        
        # Verify checksums
        if [ -f "sbom/checksums.txt" ]; then
          echo "✅ Checksums found"
          cd sbom
          sha256sum -c checksums.txt --ignore-missing
          cd ..
        fi
        
        echo ""
        echo "SBOM verification complete"

    - name: Generate verification summary
      if: always()
      run: |
        echo "# SBOM Verification" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "SBOM files verified successfully ✅" >> $GITHUB_STEP_SUMMARY
