name: Generate SBOM

on:
  push:
    branches: [ main, master, work ]
  pull_request:
    branches: [ main, master, work ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  generate-sbom:
    name: Generate Software Bill of Materials
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download SBOM artifacts
      uses: actions/download-artifact@v6
      with:
        name: sbom-${{ github.sha }}
        path: ./sbom

    - name: Verify SBOM files
      run: |
        echo "Verifying SBOM files..."
        
        # Check if main SBOM file exists
        if [ -f "sbom/sbom-root.json" ]; then
          echo "✅ Main SBOM file found"
          # Validate JSON format
          cat sbom/sbom-root.json | jq . > /dev/null && echo "✅ SBOM JSON is valid"
        else
          echo "❌ Main SBOM file not found"
          exit 1
        fi
        
        # Check dependency list
        if [ -f "sbom/dependencies.md" ]; then
          echo "✅ Dependency list found"
          DEPS=$(cat sbom/dependencies.md | wc -l)
          echo "  Dependencies listed: $DEPS lines"
        fi
        
        # Check license report
        if [ -f "sbom/licenses.md" ]; then
          echo "✅ License report found"
        fi
        
        # Verify checksums
        if [ -f "sbom/checksums.txt" ]; then
          echo "✅ Checksums found"
          cd sbom
          sha256sum -c checksums.txt --ignore-missing
          cd ..
        fi
        
        echo ""
        echo "SBOM verification complete"

    - name: Generate verification summary
      if: always()
      run: |
        echo "# SBOM Verification" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "SBOM files verified successfully ✅" >> $GITHUB_STEP_SUMMARY
