name: Staging Smoke Tests

on:
  pull_request:
    branches: [work]
  workflow_dispatch:

jobs:
  smoke:
    name: Staging Smoke Tests
    runs-on: ubuntu-latest
    env:
      STAGING_SMOKE_BASE_URL: ${{ secrets.STAGING_SMOKE_BASE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.4
          run_install: true

      - name: Verify staging smoke test base URL
        run: |
          if [ -z "${STAGING_SMOKE_BASE_URL:-}" ]; then
            echo "Configure the STAGING_SMOKE_BASE_URL secret for smoke testing." >&2
            exit 1
          fi

      - name: Install Playwright browsers
        run: pnpm --filter @avocat-ai/web exec playwright install --with-deps

      - name: Run staging smoke tests
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ secrets.STAGING_SMOKE_BASE_URL }}
        run: |
          set -euo pipefail
          pnpm test:smoke 2>&1 | tee staging-smoke.log

      - name: Upload smoke test log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: staging-smoke-log
          path: staging-smoke.log
